feat: update function and status codes
cryptlex/lexfloatclient-c pull request #3
Opened 2024-08-19 10:38 UTC by muneebkq

add missing function and status code

2024-08-21 15:18 UTC, ahmad-kemsan commented on examples/LexFloatClient.h
> +
FUNCTION: GetFloatingLicenseMode()

2024-08-21 15:20 UTC, ahmad-kemsan requested changes
Please updated the function docs.

2024-08-22 05:03 UTC, muneebkq commented on examples/LexFloatClient.h
> +
refactored

2024-08-22 09:53 UTC, ahmad-kemsan approved these changes

2024-08-22 09:54 UTC, ahmad-kemsan commented
@adnan-kamili I was unable to merge this to the main. The PR has been approved.

2024-09-20 10:45 UTC, adnan-kamili approved these changes

2024-09-20 10:45 UTC, merged